import type { TrialLocation } from "./types";

export const initialLocations: TrialLocation[] = [
  {
    id: "loc-001",
    name: "Negev Desert Test Range",
    status: "Active",
    coordinates: "30.8754° N, 34.7925° E",
    accessCode: "NVG-7741-DELTA",
    contactName: "Capt. Mira Adler",
    contactPhone: "+972-52-441-8890",
    terrain: "Desert",
    files: [],
    lastUpdated: "2026-09-16T14:22:00Z",
    hardware: [
      {
        id: "hw-101",
        name: "Seismic Array Alpha",
        technician: "Lt. Yonatan Reis",
        coordinates: "30.8761° N, 34.7918° E",
        placementNotes: "Buried 1.2m; oriented along ridge line.",
        notes: "Baseline calibration completed at 06:40. Minor wind interference noted.",
        status: "Operational",
        files: [
          {
            id: "f-1",
            name: "seismic_baseline_0916.csv",
            type: "text/csv",
            size: 248320,
            uploadedAt: "2026-09-16T07:05:00Z",
          },
          {
            id: "f-2",
            name: "array_placement_photo.jpg",
            type: "image/jpeg",
            size: 1844224,
            uploadedAt: "2026-09-16T06:52:00Z",
          },
        ],
      },
      {
        id: "hw-102",
        name: "Optical Mast OM-7",
        technician: "Sgt. Dana Halevi",
        coordinates: "30.8748° N, 34.7933° E",
        placementNotes: "Elevated tripod on packed sand pad.",
        notes: "Lens cleaned; thermal channel stable.",
        status: "Operational",
        files: [
          {
            id: "f-3",
            name: "om7_voice_note.m4a",
            type: "audio/mp4",
            size: 912000,
            uploadedAt: "2026-09-15T18:11:00Z",
          },
        ],
      },
    ],
  },
  {
    id: "loc-002",
    name: "Northern Forest Site 4",
    status: "Active",
    coordinates: "33.0412° N, 35.2789° E",
    accessCode: "NFS-4-BRAVO-19",
    contactName: "Maj. Eli Carmel",
    contactPhone: "+972-54-220-1173",
    terrain: "Forest",
    files: [],
    lastUpdated: "2026-09-16T19:04:00Z",
    hardware: [
      {
        id: "hw-201",
        name: "Acoustic Node 02",
        technician: "Cpl. Noa Biton",
        coordinates: "33.0418° N, 35.2774° E",
        placementNotes: "Mounted 4.5m on east-facing trunk.",
        notes: "Signal drop observed 18:42–18:51. Suspected canopy moisture.",
        status: "Degraded",
        files: [
          {
            id: "f-4",
            name: "acoustic_log_0916.csv",
            type: "text/csv",
            size: 512880,
            uploadedAt: "2026-09-16T19:00:00Z",
          },
          {
            id: "f-5",
            name: "signal_drop_debrief.pdf",
            type: "application/pdf",
            size: 320112,
            uploadedAt: "2026-09-16T19:12:00Z",
          },
          {
            id: "f-6",
            name: "node02_field_note.m4a",
            type: "audio/mp4",
            size: 640400,
            uploadedAt: "2026-09-16T18:55:00Z",
          },
        ],
      },
      {
        id: "hw-202",
        name: "RF Perimeter Beacon",
        technician: "Sgt. Avi Mor",
        coordinates: "33.0405° N, 35.2798° E",
        placementNotes: "Clearing edge; 2m mast.",
        notes: "Battery swap scheduled for next cycle.",
        status: "Operational",
        files: [],
      },
      {
        id: "hw-203",
        name: "Weather Microstation WX-4",
        technician: "Cpl. Noa Biton",
        coordinates: "33.0410° N, 35.2781° E",
        placementNotes: "Open canopy pocket; calibrated humidity probe.",
        notes: "Humidity spike correlates with acoustic drop window.",
        status: "Operational",
        files: [
          {
            id: "f-7",
            name: "wx4_humidity_trace.csv",
            type: "text/csv",
            size: 188440,
            uploadedAt: "2026-09-16T19:08:00Z",
          },
        ],
      },
    ],
  },
  {
    id: "loc-003",
    name: "Coastal Observation Point Kilo",
    status: "Standby",
    coordinates: "32.7940° N, 34.9896° E",
    accessCode: "COP-K-5510",
    contactName: "Lt. Col. Sara Ben-Ami",
    contactPhone: "+972-50-883-4412",
    terrain: "Coastal",
    files: [],
    lastUpdated: "2026-09-15T11:30:00Z",
    hardware: [
      {
        id: "hw-301",
        name: "Maritime Radar Pod",
        technician: "PO1 Ronen Shahar",
        coordinates: "32.7944° N, 34.9889° E",
        placementNotes: "Cliff shelf; salt-protection housing engaged.",
        notes: "Awaiting sea-state trial window.",
        status: "Maintenance",
        files: [
          {
            id: "f-8",
            name: "radar_maintenance_checklist.pdf",
            type: "application/pdf",
            size: 144200,
            uploadedAt: "2026-09-15T10:40:00Z",
          },
        ],
      },
    ],
  },
  {
    id: "loc-004",
    name: "Highland Ridge Echo",
    status: "Debrief",
    coordinates: "31.7683° N, 35.2137° E",
    accessCode: "HRE-88-ECHO",
    contactName: "Capt. Tal Mizrahi",
    contactPhone: "+972-53-771-2290",
    terrain: "Mountain",
    files: [],
    lastUpdated: "2026-09-14T16:45:00Z",
    hardware: [
      {
        id: "hw-401",
        name: "Comms Relay CR-12",
        technician: "Sgt. Ido Kaplan",
        coordinates: "31.7690° N, 35.2129° E",
        placementNotes: "Summit rock pad; guy-wired.",
        notes: "Trial complete. Awaiting archival packaging.",
        status: "Offline",
        files: [
          {
            id: "f-9",
            name: "ridge_echo_final_log.csv",
            type: "text/csv",
            size: 902100,
            uploadedAt: "2026-09-14T16:20:00Z",
          },
        ],
      },
    ],
  },
];
