import type { Region } from "./types";

export const initialRegions: Region[] = [
  {
    id: "reg-north",
    name: "Northern Israel",
    locations: [
      {
        id: "loc-galilee",
        name: "Galilee Range Alpha",
        status: "Active",
        coordinates: "32.9120° N, 35.2920° E",
        accessCode: "GAL-A-4410",
        contactName: "Maj. Eli Carmel",
        contactPhone: "+972-54-220-1173",
        terrain: "Forest",
        files: [
          {
            id: "f-site-1",
            name: "galilee_site_brief.pdf",
            type: "application/pdf",
            size: 288400,
            uploadedAt: "2026-09-16T08:10:00Z",
          },
        ],
        lastUpdated: "2026-09-16T19:04:00Z",
        hardware: [
          {
            id: "hw-ac-02",
            name: "Acoustic Sensor B",
            category: "Sensor",
            technician: "Cpl. Noa Biton",
            coordinates: "32.9128° N, 35.2911° E",
            placementNotes: "Mounted 4.5m on east-facing trunk.",
            notes:
              "Signal drop observed 18:42–18:51. Suspected canopy moisture.",
            status: "Degraded",
            files: [
              {
                id: "f-4",
                name: "acoustic_log_0916.csv",
                type: "text/csv",
                size: 512880,
                uploadedAt: "2026-09-16T19:00:00Z",
              },
              {
                id: "f-6",
                name: "node02_field_note.m4a",
                type: "audio/mp4",
                size: 640400,
                uploadedAt: "2026-09-16T18:55:00Z",
              },
            ],
          },
          {
            id: "hw-wx-4",
            name: "Weather Microstation WX-4",
            category: "Sensor",
            technician: "Cpl. Noa Biton",
            coordinates: "32.9122° N, 35.2918° E",
            placementNotes: "Open canopy pocket; calibrated humidity probe.",
            notes: "Humidity spike correlates with acoustic drop window.",
            status: "Operational",
            files: [
              {
                id: "f-7",
                name: "wx4_humidity_trace.csv",
                type: "text/csv",
                size: 188440,
                uploadedAt: "2026-09-16T19:08:00Z",
              },
            ],
          },
          {
            id: "hw-log-x1",
            name: "Data Logger X1",
            category: "Logger",
            technician: "Sgt. Avi Mor",
            coordinates: "32.9116° N, 35.2925° E",
            placementNotes: "Hardened enclosure at trail junction.",
            notes: "Buffer healthy; sync every 15 minutes.",
            status: "Operational",
            files: [],
          },
        ],
      },
      {
        id: "loc-golan",
        name: "Golan Heights Site 2",
        status: "Active",
        coordinates: "33.1205° N, 35.7802° E",
        accessCode: "GHS-2-BRAVO",
        contactName: "Capt. Tal Mizrahi",
        contactPhone: "+972-53-771-2290",
        terrain: "Mountain",
        files: [],
        lastUpdated: "2026-09-15T16:20:00Z",
        hardware: [
          {
            id: "hw-seis-01",
            name: "Seismic Array 01",
            category: "Sensor",
            technician: "Lt. Yonatan Reis",
            coordinates: "33.1210° N, 35.7794° E",
            placementNotes: "Triaxial array on basalt shelf.",
            notes: "Calibration nominal.",
            status: "Operational",
            files: [
              {
                id: "f-g1",
                name: "seismic_array01_baseline.csv",
                type: "text/csv",
                size: 402110,
                uploadedAt: "2026-09-15T12:00:00Z",
              },
            ],
          },
          {
            id: "hw-freq-a",
            name: "Frequency Logger Alpha",
            category: "Logger",
            technician: "Sgt. Ido Kaplan",
            coordinates: "33.1201° N, 35.7809° E",
            placementNotes: "Adjacent to relay mast.",
            notes: "Awaiting overnight capture window.",
            status: "Operational",
            files: [],
          },
        ],
      },
    ],
  },
  {
    id: "reg-south",
    name: "Southern Israel",
    locations: [
      {
        id: "loc-negev",
        name: "Negev Desert Range",
        status: "Active",
        coordinates: "30.8754° N, 34.7925° E",
        accessCode: "NVG-7741-DELTA",
        contactName: "Capt. Mira Adler",
        contactPhone: "+972-52-441-8890",
        terrain: "Desert",
        files: [],
        lastUpdated: "2026-09-16T14:22:00Z",
        hardware: [
          {
            id: "hw-101",
            name: "Seismic Array Alpha",
            category: "Sensor",
            technician: "Lt. Yonatan Reis",
            coordinates: "30.8761° N, 34.7918° E",
            placementNotes: "Buried 1.2m; oriented along ridge line.",
            notes:
              "Baseline calibration completed at 06:40. Minor wind interference noted.",
            status: "Operational",
            files: [
              {
                id: "f-1",
                name: "seismic_baseline_0916.csv",
                type: "text/csv",
                size: 248320,
                uploadedAt: "2026-09-16T07:05:00Z",
              },
              {
                id: "f-2",
                name: "array_placement_photo.jpg",
                type: "image/jpeg",
                size: 1844224,
                uploadedAt: "2026-09-16T06:52:00Z",
              },
            ],
          },
          {
            id: "hw-102",
            name: "Optical Mast OM-7",
            category: "Sensor",
            technician: "Sgt. Dana Halevi",
            coordinates: "30.8748° N, 34.7933° E",
            placementNotes: "Elevated tripod on packed sand pad.",
            notes: "Lens cleaned; thermal channel stable.",
            status: "Operational",
            files: [
              {
                id: "f-3",
                name: "om7_voice_note.m4a",
                type: "audio/mp4",
                size: 912000,
                uploadedAt: "2026-09-15T18:11:00Z",
              },
            ],
          },
          {
            id: "hw-negev-log",
            name: "Data Logger X1",
            category: "Logger",
            technician: "Sgt. Dana Halevi",
            coordinates: "30.8750° N, 34.7928° E",
            placementNotes: "Shaded bay next to command tent.",
            notes: "Storage at 62%.",
            status: "Operational",
            files: [],
          },
        ],
      },
      {
        id: "loc-ramon",
        name: "Ramon Crater Site 1",
        status: "Standby",
        coordinates: "30.5800° N, 34.8020° E",
        accessCode: "RCS-1-ECHO",
        contactName: "Lt. Col. Sara Ben-Ami",
        contactPhone: "+972-50-883-4412",
        terrain: "Desert",
        files: [],
        lastUpdated: "2026-09-14T11:30:00Z",
        hardware: [
          {
            id: "hw-ramon-s",
            name: "Acoustic Sensor B",
            category: "Sensor",
            technician: "PO1 Ronen Shahar",
            coordinates: "30.5804° N, 34.8014° E",
            placementNotes: "Rim overlook; wind baffles installed.",
            notes: "Standby pending trial window.",
            status: "Maintenance",
            files: [],
          },
          {
            id: "hw-ramon-l",
            name: "Frequency Logger Alpha",
            category: "Logger",
            technician: "PO1 Ronen Shahar",
            coordinates: "30.5796° N, 34.8026° E",
            placementNotes: "Sheltered ledge below rim.",
            notes: "Firmware updated.",
            status: "Operational",
            files: [
              {
                id: "f-8",
                name: "ramon_precheck.pdf",
                type: "application/pdf",
                size: 144200,
                uploadedAt: "2026-09-14T10:40:00Z",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "reg-ca",
    name: "California",
    locations: [
      {
        id: "loc-mojave",
        name: "Mojave Test Center",
        status: "Debrief",
        coordinates: "35.0594° N, 118.1516° W",
        accessCode: "MTC-88-WEST",
        contactName: "Capt. Jordan Hale",
        contactPhone: "+1-661-555-0198",
        terrain: "Open Field",
        files: [
          {
            id: "f-moj-site",
            name: "mojave_closeout_notes.pdf",
            type: "application/pdf",
            size: 210440,
            uploadedAt: "2026-09-13T17:00:00Z",
          },
        ],
        lastUpdated: "2026-09-13T17:10:00Z",
        hardware: [
          {
            id: "hw-moj-s",
            name: "Seismic Array 01",
            category: "Sensor",
            technician: "Spec. Riley Chen",
            coordinates: "35.0601° N, 118.1522° W",
            placementNotes: "Dry lake bed grid A3.",
            notes: "Trial complete. Packaging for archive.",
            status: "Offline",
            files: [
              {
                id: "f-9",
                name: "mojave_final_log.csv",
                type: "text/csv",
                size: 902100,
                uploadedAt: "2026-09-13T16:20:00Z",
              },
            ],
          },
          {
            id: "hw-moj-l",
            name: "Data Logger X1",
            category: "Logger",
            technician: "Spec. Riley Chen",
            coordinates: "35.0590° N, 118.1510° W",
            placementNotes: "Command trailer rack B.",
            notes: "Export complete.",
            status: "Offline",
            files: [],
          },
        ],
      },
    ],
  },
];
